[[education]]
degree = "Bsc. IT (Hons) Networking & IT Security"
uni = "London Metropolitan University"
year = "2017 — 2021"
summary = "Overall, this course gave me a strong foundation of knowledge in computer networks, network security, and cyber security. It has given me the tools and understanding to work in this field and be able to design, implement, and manage secure web and networks."

[[education]]
degree = "Mobile Solution Development"
uni = "Conestoga College"
year = "2024 — Present"
summary = "Learning Android / iOS and more..."