[skill]
name = "fullstack Dev && DevOps"
description = "3+ years expertise in full stack development. experienced in DevOps practices for end-to-end delivery of scalable and secure applications."

[skill.ToolsTech]
Languages = ["rust","nodejs/ts", "python", "kotlin", "c#", "swift"]
Databases = ["postgres", "mongodb", "redis"]
"Cloud Services" = ["AWS", "GCP", "Azure"]
Containers = ["Docker", "Kubernetes"]
"Version Control" = ["git/github/gitlab", "actions", "pipelines"]
API = ["RESTful API", "Postman", "Swagger", "API Security"]
Scripting = ["bash", "zsh", "python"]
Editors = ["Vim", "VSCode"]
OS = ["linux (Arch, Debian)"]